### ISSUE TITLE
Add calculations for vertical velocities

### ISSUE THREAD

**Issue by glugeorge** [ldeo-glaciology/XApRES_old#5]
Loosely adapt ImpDAR's phase2range function and assign to a class in ApRESDefs

**Comment by jkingslake** [comment]
Yes! This would be great!
Do you think it makes sense to add this to the FormProfile method of the ChirpObject class
[here](https://github.com/ldeo-glaciology/XApRES/blob/4e4f08663cad82a4fd7fac17d126e32b9f04a3b1/src/XApRES/ApRESDefs.py#L744). 
-- so that when you form a profile you also always compute the fine range.

It would also be nice to have a simple way of applying this to the data once it is already stored in an xarray --- a method of the xapres class that calls ChirpObject.FormProfile with a xarray contained the ApRES data as an input.

**Comment by glugeorge** [comment]
I'm quite close to adding this, the math is all there (adapted from ImpDAR), and it is nearly incorporated properly into the xarray. How do you envision the final structure to look? I.e., should the fine range adjustment be built into the profile_range dimension, or should it be its own?  Here's a screenshot of the structure I have so far:
![image](https://user-images.githubusercontent.com/25989736/205369375-8bfbf2c8-be46-49e2-9724-f33dd5b9dd44.png)

As of now, even though the shape of the profile_fine variable is the same as the shape of profile_range inside the _burst_to_xarray function, when everything gets concatenated together, it is extended. I'm in the midst of investigating this (I think I'm missing a single operation in the function calling the burst_to_xarray function), but it would be nice to get an agreement on the envisioned strucutre first.

**Comment by jkingslake** [comment]
nice work. 

The profiles get cropped [here](https://github.com/ldeo-glaciology/XApRES/blob/4e4f08663cad82a4fd7fac17d126e32b9f04a3b1/src/XApRES/ApRESDefs.py#L377)
to a given depth are you doing the same cropping for the profile fine?

I think `profile_range` and 'profile_fine` should have the same length in the end, right?

**Comment by glugeorge** [comment]
Summarizing takeaways from yesterday's discussion. The new plan for adding in phase2range will be as an external function outside of class objects. The reasoning behind this is that it can operate on the xarray after it has been generated to determine velocities from phase differences between time steps. It can also be repurposed to use for calculating fine range adjustments for range calculations. Regardless, it was determined that it'd be most flexible to leave it outside of the classes and focus on setting up the xarrays properly for the phase2range function to operate on.

**Comment by glugeorge** [comment]
Updated title to be more relevant to what I'm trying to address. My latest commit to my fork now has the code for calculating the range_difference/velocity between two individual bursts. It doesn't quite work for an xarray dataset containing multiple bursts quite yet. Here is my example notebook for progress thus far: https://nbviewer.org/github/glugeorge/XApRES/blob/main/notebooks/tests/usingXApRES_velocities.ipynb

#9

**Comment by jkingslake** [comment]
should we move this discussion over to the new repo https://github.com/ldeo-glaciology/xapres_package, if that is where we are doing the work now?

I am thinking that we should try to archive this repo, so we dont get confused between this one and the one we are working on now.

**Comment by glugeorge** [comment]
Yeah that sounds good. I'll add it in!
